export const MOVIE_ACTION_TYPE = {
    SET_MOVIE_POPULAR: 'movie/SET_MOVIE_POPULAR',
    SET_MOVIE_TOPRATE: 'movie/SET_MOVIE_TOPRATE',
    SET_MOVIE_UPCOMING: 'movie/SET_MOVIE_UPCOMING',
    SEARCH_MOVIE: 'movie_SEARCH_MOVIE'
}